### ISSUE TITLE
[feat]: Initial Project Setup and Configuration

### ISSUE THREAD

**Issue by ngkhang** [ngkhang/airbnb-nextjs#1]
### Feature description

This issue tracks the setup, configures the development environment, and establishes the foundational architecture and associated technologies for a project development workflow.

### Tasks

- [x] Initialize Next.js 14 project with TypeScript
- [x] Configure ESLint and Prettier
- [x] Setup Husky with pre-commit hooks
- [x] Setup linting commit with lint-staged and commit format rules with Commitlint and Committizen
- [x] Setup Tailwind CSS and Shadcn/ui
- [ ] Setup basic folder structure
- [x] Set up Zod schemas
- [x] Setup React Hook Form for form handling
- [x] Setup static content in multiple languages with `next-intl`
- [x] Setup `http` instance based on Fetch
- [x] Setup state management

### Additional Context

Additional details here...
